name: CD Pipeline

on:
  push:
    branches: [ "staging" ]

jobs:

  build:
    runs-on:
      group: Default

    steps:
      - name: Pull Docker image
        run: sudo docker pull nicolaspineda255/digital-photography-backend:latest
      - name: Delete Old docker container
        run: sudo docker rm -f digital-photography-backend-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name digital-photography-backend-container nicolaspineda255/digital-photography-backend
